spring:
  mail:
    host: ${MAIL_HOST:smtp.yandex.ru}
    port: ${MAIL_PORT:465}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    email: ${EMAIL}
    protocol: ${MAIL_PROTOCOL:smtps}
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: ${PG_URL:jdbc:postgresql://localhost:5432/t1openschool}
    username: ${PG_ROOT:postgres}
    password: ${PG_PASS:admin}
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: ${HIKARI_MAXIMUM_POOL_SIZE:5}
      jdbc-url: ${PG_URL:jdbc:postgresql://localhost:5432/t1openschool}
      schema: public
springdoc:
  swagger-ui:
    path: api
t1:
  kafka:
    bootstrap:
      server: localhost:9092
    consumer:
      group-id: t1openschool
      max.poll.records: 10
    producer:
      enable: true
    topic:
      task_status: task_status
    listener:
      poll-timeout: 1000